### ISSUE TITLE
Empty table

### ISSUE THREAD

**Issue by SasiKiranK** [adnanonline/chrome-passwords#1]
I have found the Login Data file in the profile folder. But it doesn;t have any login information.
Login table is empty.
I have deleted that file and checked in chrome, still, it can pull up the saved passwords.
I assume the latest version Chrome stores the password somewhere else.

I am using Ubuntu on and Chrome Version 57.0.2987.110 (64-bit)
Attached the screenshot for ref http://nimb.ws/rDp5Xm

**Comment by adnan-alhomssi** [comment]
Hello,
Sorry for late answer, I have tried only on Windows and it is still working
with the latest version.
I will write you later when I check it on ubuntu.
Thanks for the report.

On Mon, Aug 14, 2017 at 1:24 PM, Sasikiran Kesavan <notifications@github.com

**Comment by adnan-alhomssi** [comment]
Quick note: the implementation decrypt passwords using windows API so it
targets only windows family

On Aug 14, 2017 1:24 PM, "Sasikiran Kesavan" <notifications@github.com>
wrote:

I have found the Login Data file in the profile folder. But it doesn;t have
any login information.
Login table is empty.
I have deleted that file and checked in chrome, still, it can pull up the
saved passwords.
I assume the latest version Chrome stores the password somewhere else.

I am using Ubuntu on and Chrome Version 57.0.2987.110 (64-bit)
Attached the screenshot for ref http://nimb.ws/rDp5Xm

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adnanonline/chrome-passwords/issues/1>, or mute the
thread
